### ISSUE TITLE
Missing Info.plist file in iOS framework

### ISSUE THREAD

**Issue by ezathashim** [NMSSH/NMSSH#144]
I am compiling from source for iOS. Everything works fine when I use the framework in OS X, but when I try to use the simulator, I get this error:

2015-07-21 9:14:58.803 PM com.apple.CoreSimulator.CoreSimulatorService[4326]: Error Domain=LaunchServicesError Code=0 "The operation couldn’t be completed. (LaunchServicesError error 0.)" UserInfo=0x7fbf3c60ccf0 {Error=PackageInspectionFailed, ErrorDescription=Failed to load Info.plist from bundle at path /Users/ezat/Library/Developer/CoreSimulator/Devices/EDAD2677-B611-43B5-842A-ABC09D1A54F0/data/Library/Caches/com.apple.mobile.installd.staging/temp.PLoi5C/extracted/NopaliMobileLicenseSupport.app/Frameworks/NMSSH.framework}

It seems that simulator needs an Info.plist file. I tried adding a fake one, but then there another error comes up stating that the plist is missing a CFBundleIdentifier.

Are there any workarounds that you know of?

Thanks

- Ezat
![screenshot_829](https://cloud.githubusercontent.com/assets/5372535/8815956/59d3c5c6-2fee-11e5-87f1-a9a655a38c7f.png)

**Comment by highpockets** [comment]
You may have already found the answer to this, but just incase someone else is reading, this problem drove me crazy, so I thought I would let all looking for an answer know how I solved it..

1. I removed references and completely deleted the framework NMSHH.framewark from my Xcode project.

2. Opened Simulator, chose Simulator/Reset Content and Settings..

3. In Xcode, I did a Product/Clean and while holding alt down, did a Product/Clean Build Folder. I think if you do the latter of the 2, Product/Clean is unnecessary, but I was grabbing at straws

4. To add the framework back to the project, I chose the target/Build Phases and added a new Copy Files phase.

5. Made destination "Frameworks", TICKED "Copy only when installing" before adding the framework ( this part is in bold because it is the only thing that I changed from my original attempt ) added the framework to the copy files phase.

My blood pressure is back to normal now..

Hope this helps..
