### ISSUE TITLE
OS X Terminal prompt access

### ISSUE THREAD

**Issue by rahul606** [NMSSH/NMSSH#188]
Hi, 

I am developing OS X application to install software via ssh. I found this project really interesting. It is working very well to me but some of the software installation ask questions during installation like y/n and normally on terminal user has to respond. How can I do this via NMSSH ?

**Comment by Frugghi** [comment]
If you're using a packet manager probably there is an option to automatically reply yes (e.g. `-y`).

Otherwise you should use NMSSH in [shell mode](https://github.com/NMSSH/NMSSH/blob/master/NMSSH/NMSSHChannel.h#L118) and reply to the questions with the [write method](https://github.com/NMSSH/NMSSH/blob/master/NMSSH/NMSSHChannel.h#L135).

**Comment by rahul606** [comment]
thanks @Frugghi I figured it out after sometime and that is why closed the issue. My mistake I have not make the comment.
